require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/bundle/**/*'
    - 'spec/dummy/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/ExtraSpacing:
  Exclude:
    - 'db/migrate/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'db/migrate/**/*'

Style/DocumentationMethod:
  Enabled: true
  Exclude:
    - 'db/migrate/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/migrate/**/*'

Style/StringLiterals:
  Exclude:
    - 'bin/*'
    - 'spec/rails_helper.rb'

RSpec/ContextWording:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/controllers/kuberails/application_controller_spec.rb'

RSpec/FilePath:
  Exclude:
    - 'spec/lib/kuberails/errors/*'

RSpec/NestedGroups:
  Enabled: false

