require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
    - 'spec/dummy/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ClassAndModuleChildren:
  Enabled: false


Style/DocumentationMethod:
  Enabled: true

Style/StringLiterals:
  Exclude:
    - 'bin/*'
    - 'spec/rails_helper.rb'

RSpec/ContextWording:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - 'spec/lib/kuberails/errors/*'

