version: 2.1

executors:
  default:
    docker:
      - image: circleci/ruby:2.5.3-node
    working_directory: ~/workspace
    environment:
      BUNDLER_VERSION: 2.0.1

commands:
  save_bundle_cache:
    steps:
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
  restore_bundle_cache:
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-


jobs:
  bundler:
    executor:
      name: default
    steps:
      - checkout
      - restore_bundle_cache
      - run:
          name: Install bundler v2
          command: |
            gem uninstall bundler
            gem install bundler -v ${BUNDLER_VERSION} --no-document
      - run: bundle install --jobs=4 --retry=3 --deployment
      - save_bundle_cache


workflows:
  build_and_test:
    jobs:
      - bundler
